const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/components/CommandManager.tsx');
let content = fs.readFileSync(filePath, 'utf8');

const step2Start = content.indexOf('{triggerFormStep === 2 && (');
const step3Start = content.indexOf('{triggerFormStep === 3 && (');

if (step2Start === -1 || step3Start === -1) {
  console.error("Could not find steps!");
  process.exit(1);
}

const newStep2 = `          {triggerFormStep === 2 && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl border border-[var(--theme-border,#003865)] bg-black/40 space-y-4 relative">
                <div className="flex justify-between items-start">
                  <div>
                    <h3 className="text-white font-bold text-sm flex items-center gap-2">
                      <span className="text-[var(--theme-accent,#00f0ff)]">🎯</span>
                      Target Inspector Integration & Content Display
                    </h3>
                    <p className="text-xs text-[var(--theme-muted,#80c8ff)] mt-1">
                      (Optional) Paste the specs generated by the TRIGGER'D Inspector User Script, then select a visual style to automatically generate your overlay code.
                    </p>
                  </div>
                  <button 
                    onClick={() => setTriggerFormStep(3)}
                    className="text-xs px-3 py-1.5 rounded bg-zinc-800 text-zinc-300 hover:text-white hover:bg-zinc-700 transition"
                  >
                    Skip Step ⏭️
                  </button>
                </div>
                
                <div className="space-y-2">
                  <label className="text-white font-bold flex items-center gap-1.5 text-xs">
                    Inspector Output / Specs (JSON)
                  </label>
                  <textarea 
                    id="inspector-json-input"
                    className="w-full h-24 bg-black/50 border border-[var(--theme-border,#003865)] rounded-lg p-3 text-xs font-mono text-zinc-300 focus:outline-none focus:border-[var(--theme-accent,#00f0ff)]"
                    placeholder='{\n  "selector": ".some-target-class",\n  "type": "text",\n  "url": "https://example.com"\n}'
                  ></textarea>
                </div>

                <label className="text-white font-bold flex items-center gap-1.5 text-xs pt-2">
                  Select Visual Display Style
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
                  {[
                    { id: 'glass', name: 'Glassmorphism', icon: '🪟', desc: 'Frosted glass UI' },
                    { id: 'neon', name: 'Cyber Neon', icon: '⚡', desc: 'Glowing borders' },
                    { id: 'retro', name: 'Retro RPG', icon: '👾', desc: 'Pixel dialog box' },
                    { id: 'hologram', name: 'Hologram', icon: '🔵', desc: 'Sci-fi projection' },
                    { id: 'glitch', name: 'Glitch Effect', icon: '📺', desc: 'Distorted signal' },
                    { id: 'polaroid', name: 'Polaroid', icon: '📸', desc: 'Vintage photo frame' },
                    { id: 'terminal', name: 'Terminal', icon: '💻', desc: 'Hacker console' },
                    { id: 'warning', name: 'Warning Alert', icon: '⚠️', desc: 'Red danger banner' },
                    { id: 'gold', name: 'Golden Frame', icon: '🖼️', desc: 'Ornate museum frame' },
                    { id: 'floating', name: 'Minimal Float', icon: '☁️', desc: 'Clean drop shadow' },
                    { id: 'crt', name: 'CRT Monitor', icon: '🖥️', desc: 'Old TV scanlines' },
                    { id: 'comic', name: 'Comic Panel', icon: '💥', desc: 'Pop-art style' }
                  ].map(mode => (
                    <button
                      key={mode.id}
                      type="button"
                      onClick={(e) => {
                        const jsonInput = (document.getElementById('inspector-json-input') as HTMLTextAreaElement)?.value || '{}';
                        let specs: any = { selector: '.inspector-target', type: 'text' };
                        try { 
                          if (jsonInput.trim().length > 0) specs = JSON.parse(jsonInput); 
                        } catch (err) { 
                          console.warn('Invalid JSON specs pasted');
                        }
                        
                        let customHtml = '';
                        let customCss = '';
                        let customJs = '';
                        
                        // JS Logic to update the content
                        const isImg = specs.type === 'image';
                        const isVid = specs.type === 'video';
                        const isHtml = specs.type === 'html';
                        
                        let innerContent = isImg 
                          ? \`<img class="dyn-content" src="\${specs.src || 'https://via.placeholder.com/400x300'}" />\`
                          : isVid
                          ? \`<video class="dyn-content" autoplay muted loop playsinline></video>\`
                          : isHtml
                          ? \`<div class="dyn-content">\${specs.html || 'Waiting for DOM...'}</div>\`
                          : \`<div class="dyn-content">\${specs.text || 'Waiting for data...'}</div>\`;

                        const baseJs = \`window.addEventListener('message', (e) => {\\n  if (e.data && e.data.selector === '\${specs.selector}') {\\n    const el = container.querySelector('.dyn-content');\\n    if (!el) return;\\n    if ('\${specs.type}' === 'image' && e.data.src) el.src = e.data.src;\\n    else if ('\${specs.type}' === 'video' && e.data.src) el.src = e.data.src;\\n    else if ('\${specs.type}' === 'html' && e.data.html) el.innerHTML = e.data.html;\\n    else if (e.data.text) el.textContent = e.data.text;\\n  }\\n});\`;

                        if (mode.id === 'glass') {
                          customHtml = \`<div class="glass-card">\${innerContent}</div>\`;
                          customCss = \`.glass-card { background: rgba(255,255,255,0.1); backdrop-filter: blur(16px); border: 1px solid rgba(255,255,255,0.2); padding: 24px; border-radius: 16px; box-shadow: 0 8px 32px rgba(0,0,0,0.3); color: #fff; text-align: center; font-family: sans-serif; font-size: 1.5rem; } .dyn-content { max-width: 100%; border-radius: 8px; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'neon') {
                          customHtml = \`<div class="neon-box">\${innerContent}</div>\`;
                          customCss = \`.neon-box { border: 2px solid #00f0ff; box-shadow: 0 0 10px #00f0ff, inset 0 0 10px #00f0ff; padding: 20px; border-radius: 8px; background: rgba(0,20,40,0.8); color: #fff; text-shadow: 0 0 5px #00f0ff; font-family: 'Courier New', monospace; font-size: 1.8rem; font-weight: bold; text-align: center; } .dyn-content { max-width: 100%; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'retro') {
                          customHtml = \`<div class="retro-rpg"><div class="rpg-title">SYSTEM</div>\${innerContent}</div>\`;
                          customCss = \`.retro-rpg { background: #000; border: 4px solid #fff; padding: 20px; color: #fff; font-family: 'Courier New', monospace; font-size: 1.5rem; position: relative; } .rpg-title { position: absolute; top: -14px; left: 10px; background: #000; padding: 0 8px; font-weight: bold; } .dyn-content { max-width: 100%; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'hologram') {
                          customHtml = \`<div class="holo-container"><div class="holo-projector"></div><div class="holo-content">\${innerContent}</div></div>\`;
                          customCss = \`.holo-container { display: flex; flex-direction: column; align-items: center; } .holo-content { background: rgba(0, 150, 255, 0.2); border: 1px solid #00a8ff; box-shadow: 0 0 20px #00a8ff; padding: 15px; border-radius: 4px; color: #a4e1ff; animation: holoFlicker 2s infinite; font-family: monospace; font-size: 1.4rem; } .holo-projector { width: 60px; height: 10px; background: #ccc; border-radius: 50%; box-shadow: 0 -10px 30px 10px #00a8ff; margin-top: 20px; order: 2; } @keyframes holoFlicker { 0%, 100% { opacity: 0.9; } 50% { opacity: 0.6; } } .dyn-content { max-width: 100%; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'glitch') {
                          customHtml = \`<div class="glitch-wrapper" data-text="DATA STREAM">\${innerContent}</div>\`;
                          customCss = \`.glitch-wrapper { font-family: Impact, sans-serif; font-size: 3rem; color: #fff; position: relative; text-transform: uppercase; background: rgba(0,0,0,0.8); padding: 10px 20px; border-left: 5px solid #f0f; border-right: 5px solid #0ff; } .glitch-wrapper::before, .glitch-wrapper::after { content: attr(data-text); position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.8); padding: 10px 20px; } .glitch-wrapper::before { left: 2px; text-shadow: -2px 0 #f0f; animation: glitch-anim-1 2s infinite linear alternate-reverse; } .glitch-wrapper::after { left: -2px; text-shadow: -2px 0 #0ff; animation: glitch-anim-2 3s infinite linear alternate-reverse; } @keyframes glitch-anim-1 { 0% { clip-path: inset(20% 0 80% 0); } 100% { clip-path: inset(80% 0 20% 0); } } @keyframes glitch-anim-2 { 0% { clip-path: inset(40% 0 60% 0); } 100% { clip-path: inset(60% 0 40% 0); } } .dyn-content { max-width: 100%; position: relative; z-index: 10; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'polaroid') {
                          customHtml = \`<div class="polaroid">\${innerContent}<div class="caption">Snapshot</div></div>\`;
                          customCss = \`.polaroid { background: #fff; padding: 15px 15px 40px 15px; box-shadow: 0 10px 20px rgba(0,0,0,0.5); transform: rotate(-3deg); max-width: 350px; font-family: 'Comic Sans MS', cursive, sans-serif; color: #333; text-align: center; font-size: 1.2rem; } .dyn-content { width: 100%; height: auto; background: #222; border: 1px solid #ddd; } .caption { margin-top: 15px; font-weight: bold; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'terminal') {
                          customHtml = \`<div class="terminal"><div class="term-header">root@system:~#</div><div class="term-body">\${innerContent}</div></div>\`;
                          customCss = \`.terminal { background: #000; border-radius: 8px; border: 1px solid #333; box-shadow: 0 10px 30px rgba(0,0,0,0.8); width: 400px; font-family: monospace; overflow: hidden; } .term-header { background: #222; color: #0f0; padding: 5px 10px; font-size: 0.9rem; border-bottom: 1px solid #333; } .term-body { padding: 15px; color: #0f0; font-size: 1.2rem; } .dyn-content { max-width: 100%; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'warning') {
                          customHtml = \`<div class="warning-banner"><div class="warn-stripes"></div>\${innerContent}<div class="warn-stripes"></div></div>\`;
                          customCss = \`.warning-banner { background: #ef4444; color: #fff; font-family: Impact, sans-serif; text-transform: uppercase; border: 4px solid #fff; box-shadow: 0 0 20px #ef4444; font-size: 2.5rem; text-align: center; display: flex; align-items: center; justify-content: center; overflow: hidden; } .warn-stripes { width: 40px; height: 100%; background: repeating-linear-gradient(45deg, #000, #000 10px, transparent 10px, transparent 20px); } .dyn-content { padding: 15px 30px; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'gold') {
                          customHtml = \`<div class="gold-frame">\${innerContent}</div>\`;
                          customCss = \`.gold-frame { border: 20px solid #b8860b; border-image: repeating-linear-gradient(45deg, #d4af37 0, #b8860b 10px, #d4af37 20px) 20; padding: 10px; background: #333; box-shadow: 0 15px 40px rgba(0,0,0,0.8); } .dyn-content { max-width: 100%; border: 2px solid #222; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'floating') {
                          customHtml = \`<div class="floating-ui">\${innerContent}</div>\`;
                          customCss = \`.floating-ui { background: #fff; color: #111; padding: 20px; border-radius: 12px; box-shadow: 0 20px 40px rgba(0,0,0,0.2); animation: floatUi 3s ease-in-out infinite; font-family: system-ui, sans-serif; font-size: 1.4rem; font-weight: 500; text-align: center; } @keyframes floatUi { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-15px); } } .dyn-content { max-width: 100%; border-radius: 6px; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'crt') {
                          customHtml = \`<div class="crt-monitor">\${innerContent}</div>\`;
                          customCss = \`.crt-monitor { background: #000; color: #fff; border-radius: 20px; border: 15px solid #222; padding: 20px; position: relative; box-shadow: inset 0 0 50px rgba(255,255,255,0.1), 0 20px 50px rgba(0,0,0,0.9); font-family: monospace; font-size: 1.5rem; text-align: center; } .crt-monitor::after { content: ''; position: absolute; inset: 0; background: linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 0, 0, 0.25) 50%), linear-gradient(90deg, rgba(255, 0, 0, 0.06), rgba(0, 255, 0, 0.02), rgba(0, 0, 255, 0.06)); background-size: 100% 4px, 6px 100%; pointer-events: none; border-radius: 5px; } .dyn-content { max-width: 100%; }\`;
                          customJs = baseJs;
                        } else if (mode.id === 'comic') {
                          customHtml = \`<div class="comic-panel">\${innerContent}</div>\`;
                          customCss = \`.comic-panel { background: #fff; border: 4px solid #000; padding: 20px; box-shadow: 10px 10px 0px #000; font-family: 'Comic Sans MS', cursive; font-weight: bold; font-size: 1.8rem; text-transform: uppercase; color: #000; text-align: center; position: relative; transform: rotate(-2deg); } .dyn-content { max-width: 100%; }\`;
                          customJs = baseJs;
                        }

                        setFormState(prev => ({
                          ...prev,
                          customHtml,
                          customCss,
                          customJs,
                          spriteStyle: 'custom'
                        }));
                        setTriggerFormStep(4);
                      }}
                      className="p-3 rounded-lg border border-[var(--theme-border,#003865)]/60 hover:border-[var(--theme-accent,#00f0ff)]/80 bg-[var(--theme-card-alt,#0a2540)] text-white flex flex-col items-center justify-center transition-all shadow-sm hover:shadow-[0_0_15px_rgba(0,240,255,0.2)] text-center h-24 group relative overflow-hidden"
                    >
                      <div className="absolute inset-0 bg-[var(--theme-accent,#00f0ff)] opacity-0 group-hover:opacity-10 transition-opacity"></div>
                      <span className="text-2xl mb-1 group-hover:scale-110 transition-transform">{mode.icon}</span>
                      <span className="font-bold text-[10px] leading-tight mb-1">{mode.name}</span>
                      <span className="text-[9px] text-[var(--theme-muted,#80c8ff)]">{mode.desc}</span>
                    </button>
                  ))}
                </div>

              </div>
            </div>
          )}
`;

content = content.substring(0, step2Start) + newStep2 + content.substring(step3Start);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully updated step 2 with rich visual templates and skip button!');
