const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/components/CommandManager.tsx');
let content = fs.readFileSync(filePath, 'utf8');

// 1. Locate Step 2 and Step 3
const step2Start = content.indexOf('{triggerFormStep === 2 && (');
const step3Start = content.indexOf('{triggerFormStep === 3 && (');

if (step2Start === -1 || step3Start === -1) {
  console.error("Could not find steps!");
  process.exit(1);
}

// 2. The new Step 2 content
const newStep2 = `          {triggerFormStep === 2 && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl border border-[var(--theme-border,#003865)] bg-black/40 space-y-4">
                <h3 className="text-white font-bold text-sm flex items-center gap-2">
                  <span className="text-[var(--theme-accent,#00f0ff)]">🎯</span>
                  Target Inspector Integration & Content Display
                </h3>
                <p className="text-xs text-[var(--theme-muted,#80c8ff)]">
                  Select how you want to display content. Paste the specs generated by the TRIGGER'D Inspector User Script to automatically craft your overlay code.
                </p>
                
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  {[
                    { id: 'text', name: 'Text Extractor', icon: '📝', desc: 'Mirror innerText' },
                    { id: 'image', name: 'Image Mirror', icon: '🖼️', desc: 'Extract img src' },
                    { id: 'html', name: 'HTML Clone', icon: '🧬', desc: 'Clone DOM Node' },
                    { id: 'video', name: 'Media Stream', icon: '▶️', desc: 'Mirror Video/Audio' }
                  ].map(mode => (
                    <button
                      key={mode.id}
                      type="button"
                      onClick={(e) => {
                        const btns = document.querySelectorAll('.display-mode-btn');
                        btns.forEach(btn => {
                          btn.classList.remove('ring-2', 'ring-[var(--theme-accent,#00f0ff)]');
                          btn.removeAttribute('data-selected');
                        });
                        e.currentTarget.classList.add('ring-2', 'ring-[var(--theme-accent,#00f0ff)]');
                        e.currentTarget.setAttribute('data-selected', 'true');
                      }}
                      className="display-mode-btn p-3 rounded-lg border border-[var(--theme-border,#003865)]/60 bg-[var(--theme-card-alt,#0a2540)] text-white flex flex-col items-center justify-center transition-all shadow-sm hover:shadow-[0_0_15px_rgba(0,240,255,0.2)] text-center h-24"
                    >
                      <span className="text-2xl mb-1">{mode.icon}</span>
                      <span className="font-bold text-xs">{mode.name}</span>
                    </button>
                  ))}
                </div>

                <div className="space-y-2">
                  <label className="text-white font-bold flex items-center gap-1.5 text-xs">
                    Inspector Output / Specs (JSON)
                  </label>
                  <textarea 
                    id="inspector-json-input"
                    className="w-full h-32 bg-black/50 border border-[var(--theme-border,#003865)] rounded-lg p-3 text-xs font-mono text-zinc-300 focus:outline-none focus:border-[var(--theme-accent,#00f0ff)]"
                    placeholder='{\n  "selector": ".some-target-class",\n  "type": "html",\n  "url": "https://example.com"\n}'
                  ></textarea>
                </div>

                <button
                  type="button"
                  onClick={() => {
                    const jsonInput = (document.getElementById('inspector-json-input') as HTMLTextAreaElement)?.value || '{}';
                    let specs: any = { selector: '.inspector-target' };
                    try { 
                      if (jsonInput.trim().length > 0) specs = JSON.parse(jsonInput); 
                    } catch (e) { 
                      console.warn('Invalid JSON specs pasted, using raw text as fallback');
                      specs.rawContent = jsonInput;
                    }
                    
                    const activeBtn = document.querySelector('.display-mode-btn[data-selected="true"]');
                    const mode = activeBtn ? activeBtn.querySelector('.font-bold')?.textContent : 'HTML Clone';

                    let customHtml = '';
                    let customCss = '';
                    let customJs = '';

                    const themeColor = 'var(--theme-accent, #00f0ff)';

                    if (mode === 'Text Extractor') {
                      customHtml = \`<div class="inspector-text-widget">\\n  <h2 class="dynamic-text">\${specs.text || 'Waiting for data...'}</h2>\\n</div>\`;
                      customCss = \`.inspector-text-widget {\\n  background: rgba(0, 20, 40, 0.9);\\n  border: 2px solid #00f0ff;\\n  padding: 20px;\\n  border-radius: 12px;\\n  color: #fff;\\n  font-family: monospace;\\n  box-shadow: 0 0 20px rgba(0, 240, 255, 0.5);\\n}\\n.dynamic-text { margin: 0; font-size: 2rem; }\`;
                      customJs = \`// Setup listener for Inspector Script data matching: \${specs.selector || 'target'}\\nconsole.log('Listening for text content updates...');\\nwindow.addEventListener('message', (e) => {\\n  if (e.data && e.data.selector === '\${specs.selector}') {\\n    const el = container.querySelector('.dynamic-text');\\n    if (el) el.textContent = e.data.text;\\n  }\\n});\`;
                    } else if (mode === 'Image Mirror') {
                      customHtml = \`<div class="inspector-img-widget">\\n  <img class="dynamic-img" src="\${specs.src || 'https://via.placeholder.com/400x300'}" alt="Target Mirror" />\\n</div>\`;
                      customCss = \`.inspector-img-widget {\\n  border: 4px solid #00f0ff;\\n  border-radius: 16px;\\n  overflow: hidden;\\n  box-shadow: 0 0 30px rgba(0, 240, 255, 0.6);\\n}\\n.dynamic-img {\\n  width: 100%;\\n  height: auto;\\n  display: block;\\n}\`;
                      customJs = \`// Setup listener for Image source updates\\nwindow.addEventListener('message', (e) => {\\n  if (e.data && e.data.selector === '\${specs.selector}') {\\n    const img = container.querySelector('.dynamic-img');\\n    if (img && e.data.src) img.src = e.data.src;\\n  }\\n});\`;
                    } else if (mode === 'Media Stream') {
                      customHtml = \`<div class="inspector-media-widget">\\n  <video class="dynamic-video" autoplay muted playsinline loop></video>\\n</div>\`;
                      customCss = \`.inspector-media-widget {\\n  border: 2px solid #ff0055;\\n  border-radius: 8px;\\n  overflow: hidden;\\n  box-shadow: 0 0 30px rgba(255, 0, 85, 0.6);\\n  background: #000;\\n}\\n.dynamic-video {\\n  width: 100%;\\n  max-width: 600px;\\n  display: block;\\n}\`;
                      customJs = \`// Attach to streamed canvas/video from target page\\nconsole.log('Awaiting media stream payload for \${specs.selector}...');\\n// Listen for WebRTC/MediaStream blobs or base64 stream data\\nwindow.addEventListener('message', (e) => {\\n  if (e.data && e.data.type === 'stream-frame' && e.data.selector === '\${specs.selector}') {\\n    const vid = container.querySelector('.dynamic-video');\\n    if (vid && e.data.src) vid.src = e.data.src;\\n  }\\n});\`;
                    } else {
                      // HTML Clone
                      customHtml = \`<div class="inspector-html-widget">\\n  <div class="clone-container">\${specs.html || 'Waiting for DOM clone of ' + (specs.selector || '.target') + '...'}</div>\\n</div>\`;
                      customCss = \`.inspector-html-widget {\\n  background: rgba(10, 10, 15, 0.95);\\n  border-left: 4px solid #00f0ff;\\n  padding: 16px;\\n  color: #fff;\\n}\\n.clone-container {\\n  all: initial; /* Reset styles for pure clone */\\n  font-family: sans-serif;\\n  color: white;\\n}\`;
                      customJs = \`window.addEventListener('message', (e) => {\\n  if (e.data && e.data.selector === '\${specs.selector}') {\\n    const wrap = container.querySelector('.clone-container');\\n    if (wrap && e.data.html) wrap.innerHTML = e.data.html;\\n  }\\n});\`;
                    }

                    setFormState(prev => ({
                      ...prev,
                      customHtml,
                      customCss,
                      customJs,
                      spriteStyle: 'custom'
                    }));
                    setTriggerFormStep(4);
                  }}
                  className="w-full p-3 rounded-lg bg-[var(--theme-accent,#00f0ff)] text-black font-bold hover:bg-opacity-90 transition-all flex items-center justify-center gap-2"
                >
                  <span>⚡</span> Import Specs & Generate Code
                </button>

              </div>
            </div>
          )}
`;

// Replace content between step 2 and step 3
content = content.substring(0, step2Start) + newStep2 + content.substring(step3Start);

// Update step titles
const oldSteps = `[
              { id: 1, label: 'Basic Info', desc: 'Commands & Variants', optional: false },
              { id: 2, label: 'Templates', desc: 'Premade Bases', optional: true },
              { id: 3, label: 'Behavior Traits', desc: 'Types & Examples', optional: false },`;
              
const newSteps = `[
              { id: 1, label: 'Basic Info', desc: 'Commands & Variants', optional: false },
              { id: 2, label: 'Inspector', desc: 'Target Content', optional: true },
              { id: 3, label: 'Behavior Traits', desc: 'Types & Examples', optional: false },`;

content = content.replace(oldSteps, newSteps);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully replaced step 2 with inspector integration UI!');
